FROM centos:6.9
WORKDIR /code
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone && \
    curl -o /etc/yum.repos.d/epel-6.repo http://mirrors.aliyun.com/repo/epel-6.repo && \
    curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-6.repo && \
    yum install nginx unzip php-fpm php-mbstring php-gd -y && \
    yum clean all && \
    rm -rf /var/cache/yum && \
    curl -o kodexplorer4.40.zip  http://static.kodcloud.com/update/download/kodexplorer4.40.zip && \
    unzip kodexplorer4.37.zip && \
    chown -R apache.apache . && \
    chown -R apache.apache /var/lib/nginx 
ADD nginx.conf /etc/nginx/nginx.conf
ADD init.sh /init.sh
EXPOSE 80
ENTRYPOINT ["/bin/bash","/init.sh"]
